logspout:
  image: logspout-logstash
  volumes:
    - /var/run/docker.sock:/tmp/docker.sock
  ports:
    - "8000:8000"
  environment:
    DEBUG: true
  command: logstash://logstash:5000
  links:
    - logstash:logstash

elasticsearch:
  image: elasticsearch
  ports:
    - "9200:9200"
    - "9300:9300"
  mem_limit: 300M

logstash:
  image: logstash
  ports:
    - "5000:5000"
    - "5000:5000/udp"
  environment:
    # otherwise logstash will keep sending its own logs to itself over and
    # over... not fun
    LOGSPOUT: ignore
  command: -f /tmp/foo/logstash.sample.conf
  volumes:
    - /Users/taitken/src/poc/docker-logspout:/tmp/foo
  links:
    - elasticsearch:elasticsearch

kibana:
  image: kibana
  ports:
    - "5601:5601"
  links:
    - elasticsearch:elasticsearch