logspout:
  build: logspout/
  volumes:
    - /var/run/docker.sock:/tmp/docker.sock
  ports:
    - "8000:8000"
  environment:
    DEBUG: "true"
  command: logstash://logstash:5000
  links:
    - logstash

elasticsearch:
  environment:
    LOGSPOUT: ignore
  image: elasticsearch
  ports:
    - "9200:9200"
    - "9300:9300"
  mem_limit: 300M

logstash:
  build: logstash/
  ports:
    - "5000:5000"
    - "5000:5000/udp"
  environment:
    # otherwise logstash will keep sending its own logs to itself over and
    # over... not fun
    LOGSPOUT: ignore
  command: -f /etc/logstash/conf.d/sample.conf
  links:
    - elasticsearch

kibana:
  environment:
    LOGSPOUT: ignore
  image: kibana
  ports:
    - "5601:5601"
  links:
    - elasticsearch